In [24]:
import numpy as np 
import pandas as pd

## Creating a DataFrame
Can use list, dictionary, arrays etc

In [25]:
data = { #dict 
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)

In [26]:
df  #multiple series combined

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [44]:
# Also create data frame using list! --> does not have keys

data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
# col names - headers default goes - 0,1,2,3
# row names - default always 1,2,3,4,..

columns = ["Name","Age","City","Salary"]
df2 = pd.DataFrame(data_list,columns =columns) # manually set
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [45]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

## Selection and Indexing of Columns

In [46]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [47]:
df2[["Name","City"]]
# because indexing me col names work
# for 2 -- llist of list provided

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

## Creating a new column

In [48]:
df2["Designation"] = ["Doctor","Eng.","Doctor","Eng."]
# 4 rows so have to give 4 entries only

In [49]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000        Eng.

## Removing Columns

In [50]:
df2.drop("Designation", axis=1)

# automatic axis is 0  --> horiontally removed
# but in original it is not removed

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
# Row Removal!! and inPlace also same

df2.drop(0,axis = 0)

#only shows a snapshot - but never removed from og ram

    Name  Age    City  Salary Designation
1   Anna   34   Paris   70000        Eng.
2  Peter   29  Berlin   62000      Doctor
3  Linda   42  London   85000        Eng.

In [52]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000        Eng.

In [53]:
# thats why inplace= True used1
a=df2.drop("Designation", axis=1, inplace=True)
a

In [ ]:
df2  # Now designation is permanently removed

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

**Selecting Rows**

In [55]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [56]:
df2.loc[[0,1]]
# loc- location used for rows

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

In [ ]:
df.iloc[3]

# index location

Name       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

## Selecting Subsets of Rows and Columns

In [58]:
df.loc[[0,1]][["City","Salary"]]

       City  Salary
0  New York   65000
1     Paris   70000

In [59]:
df.loc[[2,3]][["Name","Age"]]

    Name  Age
2  Peter   29
3  Linda   42

## Conditional Selection

<, =>, =<
- dataFrame ke andar he likhna hai

In [61]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
#I only want to see those people whose age is above 30
df2[df2["Age"] > 30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [ ]:
#I only want poeple whose age is above 30 and their city must be paris
df2[(df2["Age"] > 30) & (df2["City"] == 'Paris')]

# and - & 
# or -|

   Name  Age   City  Salary
1  Anna   34  Paris   70000