- Missing values -remove or fill!
- ML algo - data must not be missing and messy
- so find, remove or fill

## Search - isna()
## remove - dropna()
## Fill - fillna()

In [1]:
import numpy as np
import pandas as pd

## Finding missing Values - Identifying

- Col wise he hota hai!

In [12]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [np.nan, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)
df
#np.nan are null values

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [13]:
df.isna()
#if null value then True

       A      B      C      D
0  False   True  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [14]:
df.isna().sum()
# have to find out which row have max number of null values

A    1
B    1
C    2
D    3
dtype: int64

In [ ]:
df.isna().any()
# cols me null value hai ki nai?

A    True
B    True
C    True
D    True
dtype: bool

## Removing Missing Values

works on basis of ROWS

In [16]:
df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [ ]:
df.dropna()
# all rows had null values - so all rows dropped

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [18]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],          #changed 1st value -- row non null
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [19]:
df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [ ]:
df.dropna(thresh=3)
# atleast 3 non null values in row

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

In [21]:
df.dropna(thresh=4)

     A  B    C    D
0  1.0  1  1.0  1.0

## Filling the missing data

- Col wise hota hai!

In [23]:
df.fillna(0)

#non null values become 0

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [ ]:
df 
# same only until we say - *inplace=True*

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [ ]:
# Fill missing values with diff value for each col

#created a dict
values = {'A': 0, 'B': 100, 'C': 300, 'D': 400}
df.fillna(value=values)

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  400.0
2  0.0  3    3.0  400.0
3  4.0  4  300.0  400.0
4  5.0  5  300.0    5.0

In [26]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [ ]:
# To fill mean

df.fillna(df.mean())
# which was 3.0 whole dataframe ka

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0